import pytest

from api import eval_input

python_cases = [
    ('242/33',
     [{'title': 'SymPy', 'input': '242/33', 'output': {'type': 'Tex', 'tex': '\\frac{22}{3}'}},
      {'name': 'float_approximation', 'title': 'Floating-point approximation',
       'input': '(22/3).evalf()', 'parameters': ['digits']},
      {'name': 'pie_chart', 'title': 'Pie chart', 'source': 'extension/elementary/pie_chart.py'},
      {'name': 'continued_fraction', 'title': 'Continued fraction', 'source': 'extension/ntheory/continued_fraction.py',
       'wiki': 'Continued_fraction'}]),
    ('12',
     [{'title': 'SymPy', 'input': '12', 'output': {'type': 'Tex', 'tex': '12'}},
      {'name': 'digits', 'title': 'Digits in base-10 expansion of number', 'input': 'len(str(12))'},
      {'name': 'english_numeral', 'title': 'English numeral', 'source': 'extension/elementary/english_numeral.py',
       'wiki': 'English_numerals'},
      {'name': 'roman_numeral', 'title': 'Roman numeral', 'source': 'extension/elementary/roman_numeral.py',
       'wiki': 'Roman_numerals'},
      {'name': 'chinese_numeral', 'title': 'Chinese numeral', 'source': 'extension/elementary/chinese_numeral.py',
       'wiki': 'Chinese_numerals'},
      {'name': 'binary_form', 'title': 'Binary form', 'input': 'np.base_repr(12)', 'wiki': 'Binary_number',
       'source': 'extension/elementary/binary_form.py'},
      {'name': 'factorization', 'title': 'Factors', 'input': 'factorint(12)'},
      {'name': 'factorizationDiagram', 'title': 'Factorization Diagram',
       'input': 'factorint(12)'},
      {'name': 'modulo', 'title': 'Modulo 2 to 9', 'source': 'extension/ntheory/modulo.py',
       'wiki': 'Modulo_operation'},
      {'name': 'quadratic_residue', 'title': 'Quadratic residue', 'source': 'extension/ntheory/quadratic_residue.py',
       'wiki': 'Quadratic_residue'},
      {'name': 'primitive_root', 'title': 'Primitive root modulo n', 'source': 'extension/ntheory/primitive_root.py',
       'wiki': 'Primitive_root_modulo_n'}]),
    ('div(x**2 - 4 + x, x-2)',
     [{'input': 'div(x**2-4+x,x-2)', 'title': 'SymPy',
       'output': {'tex': '\\mathrm{div}(x^{2} + x - 4, x - 2)', 'type': 'Tex'}},
      {'input': 'div(x**2-4+x,x-2)',
       'output': {'list': [{'tex': 'x + 3', 'type': 'Tex'}, {'tex': '2', 'type': 'Tex'}], 'type': 'List'},
       'title': 'Result'}]),
    ('factor(x**2 - 1)',
     [{'input': 'factor(x**2-1)', 'title': 'SymPy',
       'output': {'tex': '\\mathrm{Factorization~of~}x^{2} - 1', 'type': 'Tex'}},
      {'input': 'factor(x**2-1)', 'title': 'Result',
       'output': {'tex': '\\left(x - 1\\right) \\left(x + 1\\right)', 'type': 'Tex'}}]),
    ('solve(x**2 + 4*x + 181, x)',
     [{'title': 'SymPy', 'input': 'solve(x**2+4*x+181,x)',
       'output': {'type': 'Tex', 'tex': '\\mathrm{solve}\\;x^{2} + 4 x + 181=0\\;\\mathrm{for}\\;x'}},
      {'title': 'Result', 'input': 'solve(x**2+4*x+181,x)',
       'output': {'type': 'List',
                  'list': [{'type': 'Tex', 'tex': '-2 - \\sqrt{177} i', 'numeric': True,
                            'expression': '-2 - sqrt(177)*I', 'approximation': '-2.0 - 13.3041346956501 i'},
                           {'type': 'Tex', 'tex': '-2 + \\sqrt{177} i', 'numeric': True,
                            'expression': '-2 + sqrt(177)*I', 'approximation': '-2.0 + 13.3041346956501 i'}]}}]),
    ('sin(2x)',
     [{'title': 'SymPy', 'input': 'sin(2*x)', 'output': {'type': 'Tex', 'tex': '\\sin{\\left(2 x \\right)}'}},
      {'name': 'trig_alternate', 'variable': 'x', 'title': 'Alternate forms', 'pre_output': ''},
      {'name': 'plot', 'variable': 'x', 'title': 'Plot',
       'parameters': ['xmin', 'xmax', 'tmin', 'tmax', 'pmin', 'pmax']},
      {'name': 'root', 'variable': 'x', 'title': 'Root', 'source': 'extension/equation/single_variable_equation.py'},
      {'name': 'diff', 'variable': 'x', 'title': 'Derivative', 'input': 'diff(sin(2*x), x)',
       'pre_output': R'\frac{\mathrm{d}}{\mathrm{d} x} \sin{\left(2 x \right)}'},
      {'name': 'integral_alternate', 'variable': 'x', 'title': 'Antiderivative forms', 'pre_output': ''},
      {'name': 'series', 'variable': 'x', 'title': 'Series expansion around 0', 'input': 'series(sin(2*x), x, 0, 10)'}
      ]),
    ('limit(tan(x), x, pi/2)',
     [{'title': 'SymPy', 'input': 'limit(tan(x),x,pi/2)',
       'output': {'type': 'Tex', 'tex': R'\lim_{x \to \frac{\pi}{2}} \tan{\left(x \right)}'}},
      {'title': 'Result', 'input': 'limit(tan(x),x,pi/2)', 'output': {'type': 'Tex', 'tex': R'\tilde{\infty}'}}]),
    ('diff(f(x)*g(x)*h(x))',
     [{'input': "diff(Function('f')(x)*Function('g')(x)*Function('h')(x))", 'title': 'SymPy',
       'output': {'tex': R'\frac{\mathrm{d}}{\mathrm{d} x} f{\left(x \right)} g{\left(x \right)} h{\left(x \right)}',
                  'type': 'Tex'}},
      {'name': 'diff', 'input': 'diff(f(x)*g(x)*h(x), x)', 'title': 'Derivative', 'variable': 'x',
       'pre_output': R'\frac{\mathrm{d}}{\mathrm{d} x} f{\left(x \right)} g{\left(x \right)} h{\left(x \right)}'}]),
    ('integrate(tan(x))',
     [{'input': 'integrate(tan(x))', 'output': {'tex': R'\int \tan{\left(x \right)}\, \mathrm{d}x', 'type': 'Tex'},
       'title': 'SymPy'},
      {'name': 'integral_alternate_fake', 'pre_output': '', 'title': 'Antiderivative forms', 'variable': 'x'},
      {'name': 'intsteps', 'input': 'integrate(tan(x), x)',
       'title': 'Integral Steps', 'variable': 'x'}]),
    ('integrate(1/(x**2 + 1), (x, 0, oo))',
     [{'title': 'SymPy', 'input': 'integrate(1/(x**2+1),(x,0,oo))',
       'output': {'type': 'Tex', 'tex': R'\int_{0}^{\infty} \frac{1}{x^{2} + 1}\, \mathrm{d}x'}},
      {'name': 'float_approximation', 'title': 'Floating-point approximation', 'input': '(pi/2).evalf()',
       'variable': 'x', 'parameters': ['digits']},
      {'name': 'integral_alternate_fake', 'title': 'Antiderivative forms', 'variable': 'x', 'pre_output': ''},
      {'name': 'intsteps', 'title': 'Integral Steps', 'input': 'integrate(1/(x**2 + 1), (x, 0, oo))',
       'variable': 'x'}]),
    ('10!!',
     [{'title': 'SymPy', 'input': 'factorial2(10)', 'output': {'type': 'Tex', 'tex': '3840'}},
      {'name': 'digits', 'title': 'Digits in base-10 expansion of number', 'input': 'len(str(3840))'},
      {'name': 'factorization', 'title': 'Factors', 'input': 'factorint(3840)'}]),
    ('totient(42)',
     [{'title': 'SymPy', 'input': 'totient(42)', 'output': {'type': 'Tex', 'tex': '12'}},
      {'name': 'totient', 'title': 'Step', 'source': 'extension/ntheory/totient.py',
       'wiki': "Euler's_totient_function"}]),
    ('totient(x)',
     [{'title': 'SymPy', 'input': 'totient(x)', 'output': {'type': 'Tex', 'tex': '\\phi\\left(x\\right)'}}]),
    ('isprime(12321)',
     [{'title': 'SymPy', 'input': 'isprime(12321)',
       'output': {'type': 'Tex', 'tex': '\\mathrm{Is~}12321\\mathrm{~prime?}'}},
      {'name': 'result', 'title': 'Result', 'input': 'isprime(12321)'},
      {'name': 'is_prime', 'title': 'Step', 'input': 'isprime(12321)', 'source': 'extension/ntheory/is_prime.py'}]),
    ('rsolve(y(n+2)-y(n+1)-y(n), y(n))',
     [{'title': 'SymPy',
       'input': "rsolve(Function('y')(n+2)-Function('y')(n+1)-Function('y')(n),Function('y')(n))",
       'output': {'type': 'Tex',
                  'tex': '\\mathrm{Solve~the~recurrence~}- y{\\left(n \\right)} - y{\\left(n + 1 \\right)} + '
                         'y{\\left(n + 2 \\right)} = 0'}},
      {'title': 'Result',
       'input': "rsolve(Function('y')(n+2)-Function('y')(n+1)-Function('y')(n),Function('y')(n))",
       'output': {'type': 'Tex',
                  'tex': 'C_{0} \\left(\\frac{1}{2} - \\frac{\\sqrt{5}}{2}\\right)^{n} + C_{1} \\left(\\frac{1}{2} + '
                         '\\frac{\\sqrt{5}}{2}\\right)^{n}'}},
      {'title': 'Simplification',
       'input': '(C0*(1 - sqrt(5))**n + C1*(1 + sqrt(5))**n)/2**n',
       'output': {'type': 'Tex',
                  'tex': '2^{- n} \\left(C_{0} \\left(1 - \\sqrt{5}\\right)^{n} + C_{1} \\left(1 + '
                         '\\sqrt{5}\\right)^{n}\\right)'}},
      None]),
    ('diophantine(x**2 - 4*x*y + 8*y**2 - 3*x + 7*y - 5)',
     [{'title': 'SymPy', 'input': 'diophantine(x**2-4*x*y+8*y**2-3*x+7*y-5)',
       'output': {'type': 'Tex',
                  'tex': '\\begin{align}&\\mathrm{Solve~the~diophantine~equation~}x^{2} - 4 x y - 3 x + 8 y^{2} + 7 y '
                         '- 5 = 0\\\\&\\mathrm{where~}(x, y)\\mathrm{~are~integers}\\end{align}'}},
      {'title': 'Result', 'input': 'diophantine(x**2-4*x*y+8*y**2-3*x+7*y-5)',
       'output': {'type': 'Table', 'titles': ('x', 'y'),
                  'rows': [[{'type': 'Tex', 'tex': '5'}, {'type': 'Tex', 'tex': '1'}],
                           [{'type': 'Tex', 'tex': '2'}, {'type': 'Tex', 'tex': '1'}]]}}]),
    ('plot(sin(x) + cos(2*x))',
     [{'input': 'plot(sin(x)+cos(2*x))', 'title': 'SymPy',
       'output': {'tex': '\\mathrm{Plot~}\\sin{\\left(x \\right)} + \\cos{\\left(2 x \\right)}', 'type': 'Tex'}},
      {'name': 'plot', 'input': ['sin(x) + cos(2*x)'], 'parameters': ['xmin', 'xmax', 'tmin', 'tmax', 'pmin', 'pmax'],
       'title': 'Plot', 'variable': 'x'}]),
    ('plot(r=1-sin(theta))',
     [{'input': 'plot(r=1-sin(theta))', 'title': 'SymPy',
       'output': {'tex': '\\mathrm{Plot~}\\left\\{ \\mathtt{\\text{r}} : 1 - \\sin{\\left(\\theta \\right)}\\right\\}',
                  'type': 'Tex'}},
      {'name': 'plot', 'input': ['r = 1 - sin(theta)'], 'parameters': ['xmin', 'xmax', 'tmin', 'tmax', 'pmin', 'pmax'],
       'title': 'Plot', 'variable': 'x'}]),
    ('π',
     [{'title': 'SymPy', 'input': 'π', 'output': {'type': 'Tex', 'tex': '\\pi'}},
      {'name': 'float_approximation', 'title': 'Floating-point approximation',
       'input': '(pi).evalf()', 'parameters': ['digits']},
      {'name': 'pie_chart', 'title': 'Pie chart', 'source': 'extension/elementary/pie_chart.py'},
      {'name': 'continued_fraction', 'title': 'Continued fraction', 'source': 'extension/ntheory/continued_fraction.py',
       'wiki': 'Continued_fraction'}]),
    ('factor(12)',
     [{'ambiguity': 'factorint(12)',
       'description': [{'type': 'Expression', 'value': 'factor'},
                       {'type': 'Text', 'value': ' factors polynomials, while '},
                       {'type': 'Expression', 'value': 'factorint'},
                       {'type': 'Text', 'value': ' factors integers.'}]},
      {'title': 'SymPy', 'input': 'factor(12)', 'output': {'type': 'Tex', 'tex': '\\mathrm{Factorization~of~}12'}},
      {'title': 'Result', 'input': 'factor(12)', 'output': {'type': 'Tex', 'tex': '12'}}]),
    ('2.1',
     [{'title': 'SymPy', 'input': '2.1', 'output': {'type': 'Tex', 'tex': '2.1'}},
      {'name': 'rational', 'title': 'Rational', 'input': "Rational('2.1')",
       'source': 'extension/elementary/rational.py'},
      {'name': 'pie_chart', 'title': 'Pie chart', 'source': 'extension/elementary/pie_chart.py'},
      {'name': 'continued_fraction', 'title': 'Continued fraction', 'source': 'extension/ntheory/continued_fraction.py',
       'wiki': 'Continued_fraction'}]),
    ('sqrt(9)',
     [{'title': 'SymPy', 'input': 'sqrt(9)', 'output': {'type': 'Tex', 'tex': '3'}}]),
    ('1+sqrt(3)i',
     [{'title': 'SymPy', 'input': '1+sqrt(3)*I', 'output': {'type': 'Tex', 'tex': R'1 + \sqrt{3} i'}},
      {'name': 'float_approximation', 'title': 'Floating-point approximation', 'input': '(1 + sqrt(3)*I).evalf()',
       'parameters': ['digits']},
      {'name': 'absolute_value', 'title': 'Absolute value', 'input': 'Abs(1 + sqrt(3)*I)',
       'pre_output': R'\left|{1 + \sqrt{3} i}\right|'},
      {'name': 'polar_angle', 'title': 'Angle in the complex plane',
       'input': 'atan2(*(1 + sqrt(3)*I).as_real_imag()[::-1]).evalf()', 'pre_output': R'\frac{\pi}{3}'},
      {'name': 'conjugate', 'title': 'Complex conjugate', 'input': 'conjugate(1 + sqrt(3)*I)',
       'pre_output': R'1 - \sqrt{3} i'}]),
    ('x+y',
     [{'title': 'SymPy', 'input': 'x+y', 'output': {'type': 'Tex', 'tex': 'x + y'}},
      {'name': 'plot_3d', 'title': '3D Plot', 'variable': 'x', 'source': 'extension/plot/plot_3d.py'},
      {'name': 'plot_contour', 'title': 'Contour Plot', 'variable': 'x', 'source': 'extension/plot/plot_contour.py'},
      {'name': 'diff', 'title': 'Derivative', 'input': 'diff(x + y, x)', 'variable': 'x',
       'pre_output': R'\frac{\partial}{\partial x} \left(x + y\right)'},
      {'name': 'integral_alternate', 'title': 'Antiderivative forms', 'variable': 'x', 'pre_output': ''},
      {'name': 'series', 'title': 'Series expansion around 0', 'input': 'series(x + y, x, 0, 10)', 'variable': 'x'}]),
    ('f(x)',
     [{'title': 'SymPy', 'input': "Function('f')(x)", 'output': {'type': 'Tex', 'tex': R'f{\left(x \right)}'}},
      {'name': 'diff', 'title': 'Derivative', 'input': 'diff(f(x), x)', 'variable': 'x',
       'pre_output': R'\frac{\mathrm{d}}{\mathrm{d} x} f{\left(x \right)}'},
      {'name': 'integral_alternate', 'title': 'Antiderivative forms', 'variable': 'x', 'pre_output': ''}]),
    ('f(x)+y',
     [{'title': 'SymPy', 'input': "Function('f')(x)+y", 'output': {'type': 'Tex', 'tex': R'y + f{\left(x \right)}'}},
      {'name': 'diff', 'title': 'Derivative', 'input': 'diff(y + f(x), x)', 'variable': 'x',
       'pre_output': R'\frac{\partial}{\partial x} \left(y + f{\left(x \right)}\right)'},
      {'name': 'integral_alternate', 'title': 'Antiderivative forms', 'variable': 'x', 'pre_output': ''}]),
    ('theta(x)',
     [{'title': 'SymPy', 'input': 'Heaviside(x)', 'output': {'type': 'Tex', 'tex': R'\theta\left(x\right)'}},
      {'name': 'plot', 'title': 'Plot', 'variable': 'x',
       'parameters': ['xmin', 'xmax', 'tmin', 'tmax', 'pmin', 'pmax']},
      {'name': 'root', 'title': 'Root', 'variable': 'x', 'source': 'extension/equation/single_variable_equation.py'},
      {'name': 'diff', 'title': 'Derivative', 'input': 'diff(Heaviside(x), x)', 'variable': 'x',
       'pre_output': R'\frac{\mathrm{d}}{\mathrm{d} x} \theta\left(x\right)'},
      {'name': 'integral_alternate', 'title': 'Antiderivative forms', 'variable': 'x', 'pre_output': ''},
      {'name': 'series', 'title': 'Series expansion around 0', 'input': 'series(Heaviside(x), x, 0, 10)',
       'variable': 'x'}]),
    ('Limit(tan(x), x, pi/2)',
     [{'title': 'SymPy', 'input': 'Limit(tan(x),x,pi/2)',
       'output': {'type': 'Tex', 'tex': R'\lim_{x \to \frac{\pi}{2}} \tan{\left(x \right)}'}},
      {'title': 'Simplification', 'input': 'zoo', 'output': {'type': 'Tex', 'tex': R'\tilde{\infty}'}},
      {'name': 'trig_alternate', 'title': 'Alternate forms', 'pre_output': ''}]),
]


@pytest.mark.parametrize('expression, expected', python_cases)
def test_python(expression: str, expected: dict):
    actual = eval_input(expression)['result']
    assert len(actual) == len(expected)
    for a, e in zip(actual, expected):
        assert e is None or a == e


nl_cases = [
    ('Is 5 even', '(5).is_even'),  # shouldn't be Is*5*even
    ('integrate x^2y with respect to y', 'integrate((x^2y), (y))'),
    ('integrate 1/x', 'integrate(1/x)'),
]


@pytest.mark.parametrize('nl, expected', nl_cases)
def test_nl(nl: str, expected: str):
    actual = eval_input(nl)['result']
    assert actual == expected
