import pytest

from gamma.logic import SymPyGamma

cases = [
    ('242/33',
     [{'title': 'SymPy', 'input': '242/33',
       'output': {'type': 'Tex', 'tex': '\\frac{22}{3}', 'numeric': True, 'expression': '22/3',
                  'approximation': '7.33333333333333'}},
      {'card': 'float_approximation', 'variable': 'None', 'title': 'Floating-point approximation',
       'input': '(22/3).evalf()', 'pre_output': '', 'parameters': ['digits']}]),
    ('12',
     [{'title': 'SymPy', 'input': '12', 'output': {'type': 'Tex', 'tex': '12'}},
      {'card': 'digits', 'variable': 'None', 'title': 'Digits in base-10 expansion of number',
       'input': 'len(str(12))', 'pre_output': '', 'parameters': []},
      {'card': 'factorization', 'variable': 'None', 'title': 'Factors less than 100',
       'input': 'factorint(12, limit=100)', 'pre_output': '', 'parameters': []},
      {'card': 'factorizationDiagram', 'variable': 'None', 'title': 'Factorization Diagram',
       'input': 'factorint(12, limit=256)', 'pre_output': '', 'parameters': []}]),
    ('div(x**2 - 4 + x, x-2)',
     [{'input': 'div(x**2-4+x,x-2)',
       'output': {'tex': '\\mathrm{div}(x^{2} + x - 4, x - 2)', 'type': 'Tex'},
       'title': 'SymPy'},
      {'input': 'div(x**2-4+x,x-2)',
       'output': {'list': [{'tex': 'x + 3', 'type': 'Tex'}, {'tex': '2', 'type': 'Tex'}], 'type': 'List'},
       'title': 'Result'}]),
    ('sin(2*x)',
     [{'title': 'SymPy', 'input': 'sin(2*x)', 'output': {'type': 'Tex', 'tex': '\\sin{\\left(2 x \\right)}'},
       'num_variables': 1, 'variables': ['x'], 'variable': 'x'},
      {'card': 'trig_alternate', 'variable': 'x', 'title': 'Alternate forms', 'input': None, 'pre_output': '',
       'parameters': []},
      {'card': 'plot', 'variable': 'x', 'title': 'Plot', 'input': None, 'pre_output': '',
       'parameters': ['xmin', 'xmax', 'tmin', 'tmax', 'pmin', 'pmax']},
      {'card': 'roots', 'variable': 'x', 'title': 'Roots', 'input': 'solve(sin(2*x), x)', 'pre_output': 'x',
       'parameters': []},
      {'card': 'diff', 'variable': 'x', 'title': 'Derivative', 'input': 'diff(sin(2*x), x)',
       'pre_output': '\\frac{d}{d x} \\sin{\\left(2 x \\right)}', 'parameters': []},
      {'card': 'integral_alternate', 'variable': 'x', 'title': 'Antiderivative forms', 'input': None, 'pre_output': '',
       'parameters': []},
      {'card': 'series', 'variable': 'x', 'title': 'Series expansion around 0', 'input': 'series(sin(2*x), x, 0, 10)',
       'pre_output': '', 'parameters': []}]),
    ('diff(f(x)*g(x)*h(x))',
     [{'input': "diff(Function('f')(x)*Function('g')(x)*Function('h')(x))", 'num_variables': 1,
       'output': {'tex': '\\frac{d}{d x} f{\\left(x \\right)} g{\\left(x \\right)} h{\\left(x \\right)}',
                  'type': 'Tex'}, 'title': 'SymPy', 'variable': 'x', 'variables': ['x']},
      {'card': 'diff', 'input': 'diff(f(x)*g(x)*h(x), x)', 'parameters': [], 'title': 'Derivative', 'variable': 'x',
       'pre_output': '\\frac{d}{d x} f{\\left(x \\right)} g{\\left(x \\right)} h{\\left(x \\right)}'},
      {'card': 'diffsteps', 'input': 'diff(f(x)*g(x)*h(x), x)', 'parameters': [], 'pre_output': '',
       'title': 'Derivative Steps', 'variable': 'x'}]),
    ('integrate(tan(x))',
     [{'input': 'integrate(tan(x))', 'output': {'tex': '\\int \\tan{\\left(x \\right)}\\, dx', 'type': 'Tex'},
       'num_variables': 1, 'title': 'SymPy', 'variable': 'x', 'variables': ['x']},
      {'card': 'integral_alternate_fake', 'input': None, 'parameters': [], 'pre_output': '',
       'title': 'Antiderivative forms', 'variable': 'x'},
      {'card': 'intsteps', 'input': 'integrate(tan(x), x)', 'parameters': [],
       'pre_output': '', 'title': 'Integral Steps', 'variable': 'x'}]),
    ('10!!',
     [{'title': 'SymPy', 'input': 'factorial2(10)', 'output': {'type': 'Tex', 'tex': '3840'}},
      {'card': 'digits', 'variable': 'None', 'title': 'Digits in base-10 expansion of number',
       'input': 'len(str(3840))', 'pre_output': '', 'parameters': []},
      {'card': 'factorization', 'variable': 'None', 'title': 'Factors less than 100',
       'input': 'factorint(3840, limit=100)', 'pre_output': '', 'parameters': []},
      {'card': 'factorizationDiagram', 'variable': 'None', 'title': 'Factorization Diagram',
       'input': 'factorint(3840, limit=256)', 'pre_output': '', 'parameters': []}]),
    ('diophantine(x**2 - 4*x*y + 8*y**2 - 3*x + 7*y - 5)',
     [{'title': 'SymPy', 'input': 'diophantine(x**2-4*x*y+8*y**2-3*x+7*y-5)',
       'output': {'type': 'Tex',
                  'tex': '\\begin{align}&\\mathrm{Solve~the~diophantine~equation~}x^{2} - 4 x y - 3 x + 8 y^{2} + 7 y '
                         '- 5 = 0\\\\&\\mathrm{where~}(x, y)\\mathrm{~are~integers}\\end{align}'}},
      {'title': 'Result', 'input': 'diophantine(x**2-4*x*y+8*y**2-3*x+7*y-5)',
       'output': {'type': 'Table', 'titles': ('x', 'y'),
                  'rows': [[{'type': 'Tex', 'tex': '5'}, {'type': 'Tex', 'tex': '1'}],
                           [{'type': 'Tex', 'tex': '2'}, {'type': 'Tex', 'tex': '1'}]]}}]),
    ('plot(sin(x) + cos(2*x))',
     [{'input': 'plot(sin(x)+cos(2*x))', 'num_variables': 1,
       'output': {'tex': '\\mathrm{Plot~}\\sin{\\left(x \\right)} + \\cos{\\left(2 x \\right)}', 'type': 'Tex'},
       'title': 'SymPy', 'variable': 'x', 'variables': ['x']},
      {'card': 'plot', 'input': ['sin(x) + cos(2*x)'], 'parameters': ['xmin', 'xmax', 'tmin', 'tmax', 'pmin', 'pmax'],
       'pre_output': '', 'title': 'Plot', 'variable': 'x'}]),
    ('plot(r=1-sin(theta))',
     [{'input': 'plot(r=1-sin(theta))', 'num_variables': 1,
       'output': {'tex': '\\mathrm{Plot~}\\left\\{ \\mathtt{\\text{r}} : 1 - \\sin{\\left(\\theta \\right)}\\right\\}',
                  'type': 'Tex'},
       'title': 'SymPy', 'variable': 'x', 'variables': ['x']},
      {'card': 'plot', 'input': ['r = 1 - sin(theta)'], 'parameters': ['xmin', 'xmax', 'tmin', 'tmax', 'pmin', 'pmax'],
       'pre_output': '', 'title': 'Plot', 'variable': 'x'}]),
]

g = SymPyGamma()


@pytest.mark.parametrize('input_str, expected', cases)
def test(input_str: str, expected: dict):
    actual = g.eval(input_str)
    assert actual == expected
